from . import instance
from . import sale
from . import stock
from . import payment
from . import log
from . import invoice
from . import attribute
from . import product_images
from . import product
from . import res_partner
